

name: build

on:
  push:
    tags: ['v*']
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "* * * * 0" # weekly on sunday

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: test
      run: |
        dotnet test

    - name: build
      run: |
        dotnet build -c release
    
    - name: Push to nuget.org
      if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
      run: dotnet nuget push '.\src\ReadLine\bin\Release\*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
